# Generated by Django 2.0.7 on 2018-07-20 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(verbose_name='bank')),
                ('big_blind', models.IntegerField(verbose_name='big_blind')),
                ('small_blind', models.IntegerField(verbose_name='small_blind')),
                ('flop_1_card', models.CharField(blank=True, max_length=20, null=True)),
                ('flop_2_card', models.CharField(blank=True, max_length=20, null=True)),
                ('flop_3_card', models.CharField(blank=True, max_length=20, null=True)),
                ('turn', models.CharField(blank=True, max_length=20, null=True)),
                ('river', models.CharField(blank=True, max_length=20, null=True)),
                ('winner', models.CharField(max_length=20, verbose_name='winner')),
            ],
        ),
        migrations.CreateModel(
            name='GameWithPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handled_card_1', models.CharField(max_length=20, unique=True, verbose_name='first_card')),
                ('handled_card_2', models.CharField(max_length=20, unique=True, verbose_name='second_card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_property', to='PokerApp.CurrentGame')),
                ('player_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_player', to='PokerApp.Bot')),
                ('player_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
