# Generated by Django 2.0.7 on 2018-07-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_balance', models.IntegerField(auto_created=True, default=1000, verbose_name='Bot_stack')),
                ('bot_name', models.CharField(max_length=20, unique=True, verbose_name='Bot_name')),
                ('bot_image', models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='Bot_image')),
            ],
        ),
    ]
