# Generated by Django 2.0.7 on 2018-07-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0002_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Bot_image'),
        ),
    ]
