# Generated by Django 2.0.7 on 2018-07-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0002_auto_20180729_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgame',
            name='big_blind_seat',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='currentgame',
            name='small_blind_seat',
            field=models.IntegerField(default=1),
        ),
    ]
