# Generated by Django 2.0.7 on 2018-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0003_auto_20180730_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamewithplayers',
            name='action_flop',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamewithplayers',
            name='action_preflop',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamewithplayers',
            name='action_river',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamewithplayers',
            name='action_turn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
