# Generated by Django 2.0.7 on 2018-07-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0005_auto_20180730_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentgame',
            name='big_blind_seat',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='currentgame',
            name='small_blind_seat',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamewithplayers',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
