# Generated by Django 2.0.7 on 2018-07-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0006_auto_20180730_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentgame',
            name='big_blind_seat',
        ),
        migrations.RemoveField(
            model_name='currentgame',
            name='small_blind_seat',
        ),
    ]
