# Generated by Django 2.0.7 on 2018-08-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0009_countseat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionOfCurrentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(auto_created=True, default='EP', max_length=10)),
            ],
        ),
    ]
