# Generated by Django 2.0.7 on 2018-08-16 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PokerApp', '0013_auto_20180810_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentgame',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
